spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    password: mypassword
    url: jdbc:mysql://localhost:3306/mydb