version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: always
    networks:
      - backend
    container_name: mysqldb
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql-vol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

volumes:
  mysql-vol:
networks:
  backend: